### ISSUE TITLE
Delayed and reserved queues

### ISSUE THREAD

**Issue by jan-carreras** [halaei/bredis#1]
Hi, first thanks for your project.

About that:

> Warning: bredis queue workers don't bother handling jobs that are delayed or reserved. So when using bredis workers, you have to have at least one redis worker as well.

How are we supposed to start a second worker with another driver (redis/bredis)? What is your suggested approach to it?

`php artisan queue:work # how we decide which driver to use?`

Thanks for your time.
--J

**Comment by halaei** [comment]
You need one redis worker per queue plus as many bredis worker per queue that is good for your project:
```
php artisan queue:work bredis --queue=q1 --sleep=0 #run as many worker as you should
php artisan queue:work redis --queue=q1 --sleep=3 #run just one to handle delayed/failes jobs as well
```
I may complete the driver to handle the delayed jobs as well, then send a PR to laravel/framework. But that makes code a little complicated.
Thanks

**Comment by jan-carreras** [comment]
Thank you very much for your quick response. You saved my day.

Wouldn't it to be as easy as calling `$this->migrate($prefixed = $this->getQueue($queue));` on your `pop` method?

I'm not familiar with the Laravel Queue codebase but that's what they seem to be doing to get the `:delayed` and `:reserved` queues back to the main queue...

Again, thanks!

**Comment by halaei** [comment]
Yes, but I don't recall why exactly I did not put that one line of code there to migrate jobs.
